// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    JzForm: typeof import('./src/components/JzForm/src/JzForm.vue')['default']
    JzMsgList: typeof import('./src/components/JzMsgList/src/JzMsgList.vue')['default']
    JzTable: typeof import('./src/components/JzTable/src/JzTable.vue')['default']
    JzTopSearch: typeof import('./src/components/JzTopSearch/src/JzTopSearch.vue')['default']
    JzUploadImage: typeof import('./src/components/JzUploadImage/src/JzUploadImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
